version: '3.8'
services:
 app:
  image: node:latest
  container_name: nodeapp
  environment:
   DB_HOST: mysql1
   DB_PORT: 3306
   DB_USER: root
   DB_PASSWORD: admin
   REACT_APP_SECRET_KEY: "79UtjtdnarvqmCxJFu5L"
  ports:
   - "31:3000"
  command: ["bin/bash"]
  volumes:
   - ./backend:/code
  depends_on:
   - mysql1 
  stdin_open: true
  tty: true
 node2:
  build: .
  container_name: reactapp
  ports:
   - "3000:3000"
  volumes:
   - ./frontend:/code
  environment:
  - CHOKIDAR_USEPOLLING=true
  - WATCHPACK_POLLING=true
  depends_on:
   - mysql1 
  stdin_open: true
  tty: true
 node4:
  image: node:latest
  container_name: testapp
  ports:
    - "32:3000"
  volumes:
    - ./backend:/code
  command: ["bin/bash"]
  stdin_open: true
  tty: true
 mysql1:
  image: mysql:5.7
  restart: always
  container_name: db1
  environment:
   - MYSQL_PASSWORD=admin
   - MYSQL_ROOT_PASSWORD=admin
  ports:
   - '3306:3306'
  volumes:
   - db:/var/lib/mysql
  stdin_open: true
  tty: true
volumes: 
  db:
     driver: local
